# -*- coding: utf-8 -*-
"""Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PGSN9UEKpsYxf-wXhcYumJ-BRzxQTZ_
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

# Example when d_model = 512 and num_heads = 8
def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size()[-1] # 64
    scaled = torch.matmul(q, k.transpose(-1, -2)) / math.sqrt(d_k) # 30 x 8 x 200 x 200
    if mask is not None:
        scaled = scaled.permute(1, 0, 2, 3) + mask
        scaled = scaled.permute(1, 0, 2, 3) # 30 x 8 x 200 x 200
    attention = F.softmax(scaled, dim=-1) # 30 x 8 x 200 x 200 in a probability distribution
    values = torch.matmul(attention, v) # 30 x 8 x 200 x 64
    return values, attention

# Example when d_model = 512 and num_heads = 8
class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()
        self.d_model = d_model # 512
        self.num_heads = num_heads # 8
        self.head_dim = d_model // num_heads # 64
        self.qkv_layer = nn.Linear(d_model , 3 * d_model) # 512 -> 1536
        self.linear_layer = nn.Linear(d_model, d_model) # 512 -> 512

    def forward(self, x, mask):
        batch_size, sequence_length, d_model = x.size() # 30 x 200 x 512
        qkv = self.qkv_layer(x) # 30 x 200 x 1536
        qkv = qkv.reshape(batch_size, sequence_length, self.num_heads, 3 * self.head_dim) # 30 x 200 x 8 x 192
        qkv = qkv.permute(0, 2, 1, 3) # 30 x 8 x 200 x 192
        q, k, v = qkv.chunk(3, dim=-1) # q,k, v = 30 x 8 x 200 x 64
        values, attention = scaled_dot_product(q, k, v, mask) # 30 x 8 x 200 x 64, 30 x 8 x 200 x 200
        values = values.permute(0, 2, 1, 3) # 30 x 200 x 8 x 64
        values = values.reshape(batch_size, sequence_length, self.num_heads * self.head_dim) # 30 x 200 x 512
        out = self.linear_layer(values) # 30 x 200 x 512
        return out

# Example when d_model = 512 and num_heads = 8
class MultiHeadCrossAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()
        self.d_model = d_model # 512
        self.num_heads = num_heads # 8
        self.head_dim = d_model // num_heads # 64
        self.kv_layer = nn.Linear(d_model , 2 * d_model) # 512 -> 1024
        self.q_layer = nn.Linear(d_model , d_model) # 512 -> 512
        self.linear_layer = nn.Linear(d_model, d_model) # 512 -> 512

    def forward(self, x, y, mask):
        batch_size, sequence_length, d_model = x.size() # in practice, this is the same for both languages...so we can technically combine with normal attention
        kv = self.kv_layer(x) # 30 x 200 x 1024
        q = self.q_layer(y) # 30 x 8 x 200 x 512
        kv = kv.reshape(batch_size, sequence_length, self.num_heads, 2 * self.head_dim) # 30 x 200 x 8 x 128
        q = q.reshape(batch_size, sequence_length, self.num_heads, self.head_dim) # 30 x 200 x 8 x 64
        kv = kv.permute(0, 2, 1, 3) # 30 x 8 x 200 x 128
        q = q.permute(0, 2, 1, 3) # 30 x 8 x 200 x 64
        k, v = kv.chunk(2, dim=-1) # k, v = 30 x 8 x 200 x 64
        # dot product attentopn requires q, k, v to be of shape (batch_size, num_heads, sequence_length, head_dim)
        values, attention = scaled_dot_product(q, k, v, mask) # We don't need the mask for cross attention, removing in outer function!
        values = values.permute(0, 2, 1, 3) # 30 x 200 x 8 x 64
        values = values.reshape(batch_size, sequence_length, d_model) # 30 x 200 x 512
        out = self.linear_layer(values) # 30 x 200 x 512
        return out

class SentenceEmbedding(nn.Module):
    def __init__(self, max_sequence_length, d_model, language_to_index, START_TOKEN, END_TOKEN, PADDING_TOKEN):
        super().__init__()
        self.vocab_size = len(language_to_index)
        self.d_model = d_model
        self.language_to_index = language_to_index
        self.embedding = nn.Embedding(self.vocab_size, d_model)
        self.positional_encoding = PositionalEncoding(max_sequence_length, d_model)
        self.START_TOKEN = START_TOKEN
        self.END_TOKEN = END_TOKEN
        self.PADDING_TOKEN = PADDING_TOKEN

    def batch_tokenize(
    sentences,
    lang,
    enc,
    language_to_index,
    start_token=True,
    end_token=True
  ):
      """
      Tokenize a batch of sentences using tiktoken encoder,
      add special tokens, and pad to max length.
      """
      tokenized = []
      for s in sentences:
          # Encode into subword IDs using tiktoken
          ids = enc.encode(s.lower())

          # Add special tokens
          if start_token:
              ids = [language_to_index[lang][START_TOKEN]] + ids
          if end_token:
              ids = ids + [language_to_index[lang][END_TOKEN]]

          tokenized.append(ids)

      # Pad to max length in this batch
      max_len = max(len(seq) for seq in tokenized)
      padded = [
          seq + [language_to_index[lang][PADDING_TOKEN]] * (max_len - len(seq))
          for seq in tokenized
      ]

      return torch.tensor(padded, dtype=torch.long)


    def tokenize(self, sentence, start_token, end_token):
        # Remove punctuation and split sentence into words
        sentence = re.sub(r'[^\w\s]', '', sentence).lower() # Remove punctuation and convert to lowercase
        words = sentence.split() # Split into words after removing punctuation

        sentence_word_indicies = [self.language_to_index[word] for word in words if word in self.language_to_index] # Look up index for each word, skipping words not in vocab

        if start_token:
            sentence_word_indicies.insert(0, self.language_to_index[self.START_TOKEN])
        if end_token:
            sentence_word_indicies.append(self.language_to_index[self.END_TOKEN])

        # Pad the sequence to max_sequence_length
        for _ in range(len(sentence_word_indicies), self.positional_encoding.max_sequence_length):
            sentence_word_indicies.append(self.language_to_index[self.PADDING_TOKEN])

        return torch.tensor(sentence_word_indicies)


    def forward(self, x, start_token, end_token): # x are batch of sentences
        x = self.batch_tokenize(x, start_token, end_token) # x is now batch of tokens
        x = self.embedding(x)
        x = self.positional_encoding(x)
        return x

class PositionalEncoding(nn.Module):
    def __init__(self, max_sequence_length, d_model):
        super().__init__()
        self.d_model = d_model
        self.max_sequence_length = max_sequence_length
        pe = torch.zeros(max_sequence_length, d_model)
        position = torch.arange(0, max_sequence_length, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        x = x + self.pe[:, :x.size(1), :]
        return x



class PositionwiseFeedForward(nn.Module):
    def __init__(self, d_model, hidden, drop_prob=0.1):
        super(PositionwiseFeedForward, self).__init__()
        self.linear1 = nn.Linear(d_model, hidden)
        self.linear2 = nn.Linear(hidden, d_model)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=drop_prob)

    def forward(self, x):
        x = self.linear1(x) # 512 -> 2048
        x = self.relu(x) # activation
        x = self.dropout(x)
        x = self.linear2(x) # 2048 -> 512
        return x

class Decoder(nn.Module):
    def __init__(self,
                 d_model,
                 ffn_hidden,
                 num_heads,
                 drop_prob,
                 num_layers,
                 max_sequence_length,
                 language_to_index,
                 START_TOKEN,
                 END_TOKEN,
                 PADDING_TOKEN):
        super().__init__()
        self.sentence_embedding = SentenceEmbedding(max_sequence_length, d_model, language_to_index, START_TOKEN, END_TOKEN, PADDING_TOKEN)
        self.layers = SequentialDecoder(*[DecoderLayer(d_model, ffn_hidden, num_heads, drop_prob) for _ in range(num_layers)])

    def forward(self, x, y, self_attention_mask, cross_attention_mask, start_token, end_token):
        y = self.sentence_embedding(y, start_token, end_token) # Encoding
        y = self.layers(x, y, self_attention_mask, cross_attention_mask) # Steps in the transformer decoder
        return y


class DecoderLayer(nn.Module):
    def __init__(self, d_model, ffn_hidden, num_heads, drop_prob):
        super(DecoderLayer, self).__init__()
        self.self_attention = MultiHeadAttention(d_model=d_model, num_heads=num_heads) # masked multi-head attention
        self.layer_norm1 = LayerNormalization(parameters_shape=[d_model]) # layer normalization
        self.dropout1 = nn.Dropout(p=drop_prob) # dropout

        self.encoder_decoder_attention = MultiHeadCrossAttention(d_model=d_model, num_heads=num_heads)
        self.layer_norm2 = LayerNormalization(parameters_shape=[d_model])
        self.dropout2 = nn.Dropout(p=drop_prob)

        self.ffn = PositionwiseFeedForward(d_model=d_model, hidden=ffn_hidden, drop_prob=drop_prob)
        self.layer_norm3 = LayerNormalization(parameters_shape=[d_model])
        self.dropout3 = nn.Dropout(p=drop_prob)

    def forward(self, x, y, self_attention_mask, cross_attention_mask):
        _y = y.clone() # residual connection
        y = self.self_attention(y, mask=self_attention_mask) # masked multi-head attention
        y = self.dropout1(y) # dropout
        y = self.layer_norm1(y + _y) # add with residual conection # 30 x 200 x 512

        _y = y.clone()
        y = self.encoder_decoder_attention(x, y, mask=cross_attention_mask) # cross attention
        y = self.dropout2(y)
        y = self.layer_norm2(y + _y)

        _y = y.clone()
        y = self.ffn(y) # feed forward 512 -> 2048 -> 512
        y = self.dropout3(y)
        y = self.layer_norm3(y + _y)
        return y

class SequentialDecoder(nn.Sequential):
    def forward(self, *inputs): # we do this to repeat the decoder process
        x, y, self_attention_mask, cross_attention_mask = inputs
        for module in self._modules.values():
            y = module(x, y, self_attention_mask, cross_attention_mask)
        return y

class EncoderLayer(nn.Module):
    def __init__(self, d_model, ffn_hidden, num_heads, drop_prob):
        super(EncoderLayer, self).__init__()
        self.attention = MultiHeadAttention(d_model=d_model, num_heads=num_heads)
        self.norm1 = LayerNormalization(parameters_shape=[d_model])
        self.dropout1 = nn.Dropout(p=drop_prob)
        self.ffn = PositionwiseFeedForward(d_model=d_model, hidden=ffn_hidden, drop_prob=drop_prob)
        self.norm2 = LayerNormalization(parameters_shape=[d_model])
        self.dropout2 = nn.Dropout(p=drop_prob)

    def forward(self, x, self_attention_mask):
        residual_x = x.clone() # 30 x 200 x 512
        x = self.attention(x, mask=self_attention_mask) # 30 x 200 x 512 multi head attention
        x = self.dropout1(x)
        x = self.norm1(x + residual_x) # normalization
        residual_x = x.clone()
        x = self.ffn(x) # 512 -> 2048 -> 512
        x = self.dropout2(x)
        x = self.norm2(x + residual_x)
        return x

class SequentialEncoder(nn.Sequential):
    def forward(self, *inputs): # do the encoder step n times
        x, self_attention_mask  = inputs
        for module in self._modules.values():
            x = module(x, self_attention_mask)
        return x

class Encoder(nn.Module):
    def __init__(self,
                 d_model,
                 ffn_hidden,
                 num_heads,
                 drop_prob,
                 num_layers,
                 max_sequence_length,
                 language_to_index,
                 START_TOKEN,
                 END_TOKEN,
                 PADDING_TOKEN):
        super().__init__()
        self.sentence_embedding = SentenceEmbedding(max_sequence_length, d_model, language_to_index, START_TOKEN, END_TOKEN, PADDING_TOKEN)
        self.layers = SequentialEncoder(*[EncoderLayer(d_model, ffn_hidden, num_heads, drop_prob)
                                      for _ in range(num_layers)])

    def forward(self, x, self_attention_mask, start_token, end_token):
        x = self.sentence_embedding(x, start_token, end_token) # embedding
        x = self.layers(x, self_attention_mask) # encoder layers
        return x
