# -*- coding: utf-8 -*-
"""
Editor de Spyder

Este es un archivo temporal.
"""

# -*- coding: utf-8 -*-
"""Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PGSN9UEKpsYxf-wXhcYumJ-BRzxQTZ_
"""


import torch
import torch.nn as nn
import torch.nn.functional as F
import math


# Example when d_model = 512 and num_heads = 8
def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size()[-1] # 64
    scaled = torch.matmul(q, k.transpose(-1, -2)) / math.sqrt(d_k) # 30 x 8 x 200 x 200
    if mask is not None:
      scaled = scaled + mask
    attention = F.softmax(scaled, dim=-1) # 30 x 8 x 200 x 200 in a probability distribution
    values = torch.matmul(attention, v) # 30 x 8 x 200 x 64
    return values, attention



class LayerNormalization(nn.Module):
    def __init__(self, parameters_shape, eps=1e-5):
        super().__init__()
        self.parameters_shape=parameters_shape
        self.eps=eps
        self.gamma = nn.Parameter(torch.ones(parameters_shape))
        self.beta =  nn.Parameter(torch.zeros(parameters_shape))

    def forward(self, inputs):
        dims = [-(i + 1) for i in range(len(self.parameters_shape))] # get the dimensions of the input
        mean = inputs.mean(dim=dims, keepdim=True) # mean maintining dimensions 30 x 200 x 1
        var = ((inputs - mean) ** 2).mean(dim=dims, keepdim=True) # variance
        std = (var + self.eps).sqrt() # standard deviation
        y = (inputs - mean) / std # normalization 30 x 200 x 512
        out = self.gamma * y + self.beta # trainable parameters
        return out
    

  
# Example when d_model = 512 and num_heads = 8
class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()
        self.d_model = d_model # 512
        self.num_heads = num_heads # 8
        self.head_dim = d_model // num_heads # 64
        self.qkv_layer = nn.Linear(d_model , 3 * d_model) # 512 -> 1536
        self.linear_layer = nn.Linear(d_model, d_model) # 512 -> 512

    def forward(self, x, mask):
        batch_size, sequence_length, d_model = x.size() # 30 x 200 x 512
        qkv = self.qkv_layer(x) # 30 x 200 x 1536
        qkv = qkv.reshape(batch_size, sequence_length, self.num_heads, 3 * self.head_dim) # 30 x 200 x 8 x 192
        qkv = qkv.permute(0, 2, 1, 3) # 30 x 8 x 200 x 192
        q, k, v = qkv.chunk(3, dim=-1) # q,k, v = 30 x 8 x 200 x 64
        values, attention = scaled_dot_product(q, k, v, mask) # 30 x 8 x 200 x 64, 30 x 8 x 200 x 200
        values = values.permute(0, 2, 1, 3) # 30 x 200 x 8 x 64
        values = values.reshape(batch_size, sequence_length, self.num_heads * self.head_dim) # 30 x 200 x 512
        out = self.linear_layer(values) # 30 x 200 x 512
        return out

# Example when d_model = 512 and num_heads = 8
class MultiHeadCrossAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()
        self.d_model = d_model # 512
        self.num_heads = num_heads # 8
        self.head_dim = d_model // num_heads # 64
        self.kv_layer = nn.Linear(d_model , 2 * d_model) # 512 -> 1024
        self.q_layer = nn.Linear(d_model , d_model) # 512 -> 512
        self.linear_layer = nn.Linear(d_model, d_model) # 512 -> 512

    def forward(self, x, y, mask):
      batch_size, enc_len, d_model = x.size()
      _, dec_len, _ = y.size()

      kv = self.kv_layer(x)  # (batch, enc_len, 2*d_model)
      q = self.q_layer(y)    # (batch, dec_len, d_model)

      # reshape
      kv = kv.reshape(batch_size, enc_len, self.num_heads, 2 * self.head_dim)
      kv = kv.permute(0, 2, 1, 3)  # (batch, heads, enc_len, 2*head_dim)

      q = q.reshape(batch_size, dec_len, self.num_heads, self.head_dim)
      q = q.permute(0, 2, 1, 3)  # (batch, heads, dec_len, head_dim)

      k, v = kv.chunk(2, dim=-1)  # split into (batch, heads, enc_len, head_dim)

      # scaled dot product attention
      values, attention = scaled_dot_product(q, k, v, mask)

      # reshape back
      values = values.permute(0, 2, 1, 3)  # (batch, dec_len, heads, head_dim)
      values = values.reshape(batch_size, dec_len, d_model)
      out = self.linear_layer(values)
      return out


class SentenceEmbedding(nn.Module):
    def __init__(self, max_sequence_length, d_model, language_to_index):
        super().__init__()
        self.vocab_size = len(language_to_index)
        self.d_model = d_model
        self.language_to_index = language_to_index
        self.embedding = nn.Embedding(self.vocab_size, d_model)
        self.positional_encoding = PositionalEncoding(max_sequence_length, d_model)


    def forward(self, x): # x are batch of sentences
        x = self.embedding(x)
        x = self.positional_encoding(x)
        return x

class PositionalEncoding(nn.Module):
    def __init__(self, max_sequence_length, d_model):
        super().__init__()
        self.d_model = d_model
        self.max_sequence_length = max_sequence_length
        pe = torch.zeros(max_sequence_length, d_model)
        position = torch.arange(0, max_sequence_length, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        x = x + self.pe[:, :x.size(1), :]
        return x



class PositionwiseFeedForward(nn.Module):
    def __init__(self, d_model, hidden, drop_prob=0.1):
        super(PositionwiseFeedForward, self).__init__()
        self.linear1 = nn.Linear(d_model, hidden)
        self.linear2 = nn.Linear(hidden, d_model)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=drop_prob)

    def forward(self, x):
        x = self.linear1(x) # 512 -> 2048
        x = self.relu(x) # activation
        x = self.dropout(x)
        x = self.linear2(x) # 2048 -> 512
        return x

class Decoder(nn.Module):
    def __init__(self,
                d_model,
                ffn_hidden,
                num_heads,
                drop_prob,
                num_layers,
                max_sequence_length,
                language_to_index):
        super().__init__()
        self.sentence_embedding = SentenceEmbedding(max_sequence_length, d_model, language_to_index)
        self.layers = SequentialDecoder(*[DecoderLayer(d_model, ffn_hidden, num_heads, drop_prob) for _ in range(num_layers)])

    def forward(self, x, y, self_attention_mask, cross_attention_mask):
        y = self.sentence_embedding(y) # Encoding
        y = self.layers(x, y, self_attention_mask, cross_attention_mask) # Steps in the transformer decoder
        return y


class DecoderLayer(nn.Module):
    def __init__(self, d_model, ffn_hidden, num_heads, drop_prob):
        super(DecoderLayer, self).__init__()
        self.self_attention = MultiHeadAttention(d_model=d_model, num_heads=num_heads) # masked multi-head attention
        self.layer_norm1 = LayerNormalization(parameters_shape=[d_model]) # layer normalization
        self.dropout1 = nn.Dropout(p=drop_prob) # dropout

        self.encoder_decoder_attention = MultiHeadCrossAttention(d_model=d_model, num_heads=num_heads)
        self.layer_norm2 = LayerNormalization(parameters_shape=[d_model])
        self.dropout2 = nn.Dropout(p=drop_prob)

        self.ffn = PositionwiseFeedForward(d_model=d_model, hidden=ffn_hidden, drop_prob=drop_prob)
        self.layer_norm3 = LayerNormalization(parameters_shape=[d_model])
        self.dropout3 = nn.Dropout(p=drop_prob)

    def forward(self, x, y, self_attention_mask, cross_attention_mask):
        _y = y.clone() # residual connection
        y = self.self_attention(y, mask=self_attention_mask) # masked multi-head attention
        y = self.dropout1(y) # dropout
        y = self.layer_norm1(y + _y) # add with residual conection # 30 x 200 x 512

        _y = y.clone()
        y = self.encoder_decoder_attention(x, y, mask=cross_attention_mask) # cross attention
        y = self.dropout2(y)
        y = self.layer_norm2(y + _y)

        _y = y.clone()
        y = self.ffn(y) # feed forward 512 -> 2048 -> 512
        y = self.dropout3(y)
        y = self.layer_norm3(y + _y)
        return y

class SequentialDecoder(nn.Sequential):
    def forward(self, *inputs): # we do this to repeat the decoder process
        x, y, self_attention_mask, cross_attention_mask = inputs
        for module in self._modules.values():
            y = module(x, y, self_attention_mask, cross_attention_mask)
        return y

class EncoderLayer(nn.Module):
    def __init__(self, d_model, ffn_hidden, num_heads, drop_prob):
        super(EncoderLayer, self).__init__()
        self.attention = MultiHeadAttention(d_model=d_model, num_heads=num_heads)
        self.norm1 = LayerNormalization(parameters_shape=[d_model])
        self.dropout1 = nn.Dropout(p=drop_prob)
        self.ffn = PositionwiseFeedForward(d_model=d_model, hidden=ffn_hidden, drop_prob=drop_prob)
        self.norm2 = LayerNormalization(parameters_shape=[d_model])
        self.dropout2 = nn.Dropout(p=drop_prob)

    def forward(self, x, self_attention_mask):
        residual_x = x.clone() # 30 x 200 x 512
        x = self.attention(x, mask=self_attention_mask) # 30 x 200 x 512 multi head attention
        x = self.dropout1(x)
        x = self.norm1(x + residual_x) # normalization
        residual_x = x.clone()
        x = self.ffn(x) # 512 -> 2048 -> 512
        x = self.dropout2(x)
        x = self.norm2(x + residual_x)
        return x

class SequentialEncoder(nn.Sequential):
    def forward(self, *inputs): # do the encoder step n times
        x, self_attention_mask  = inputs
        for module in self._modules.values():
            x = module(x, self_attention_mask)
        return x

class Encoder(nn.Module):
    def __init__(self,
                d_model,
                ffn_hidden,
                num_heads,
                drop_prob,
                num_layers,
                max_sequence_length,
                language_to_index):
        super().__init__()
        self.sentence_embedding = SentenceEmbedding(max_sequence_length, d_model, language_to_index)
        self.layers = SequentialEncoder(*[EncoderLayer(d_model, ffn_hidden, num_heads, drop_prob)
                                    for _ in range(num_layers)])

    def forward(self, x, self_attention_mask):
        x = self.sentence_embedding(x) # embedding
        x = self.layers(x, self_attention_mask) # encoder layers
        return x
